import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Paths relative to project root
const ASSETS_DIR = path.join(__dirname, '../src/assets');
const OUTPUT_FILE = path.join(__dirname, '../src/types/assets.ts');

/**
 * Generates TypeScript types for all assets in the project
 * This ensures type safety when referencing asset IDs
 */
function generateAssetTypes() {
  console.log('🔍 Scanning assets...');

  // Get background images
  const bgPath = path.join(ASSETS_DIR, 'images/backgrounds');
  const backgrounds = fs.existsSync(bgPath)
    ? fs.readdirSync(bgPath)
        .filter((f: string) => f.endsWith('.png'))
        .map((f: string) => path.parse(f).name)
    : [];

  // Get BGM files
  const bgmPath = path.join(ASSETS_DIR, 'audio/bgm');
  const bgms = fs.existsSync(bgmPath)
    ? fs.readdirSync(bgmPath)
        .filter((f: string) => ['.mp3', '.wav', '.ogg'].includes(path.extname(f)))
        .map((f: string) => path.parse(f).name)
    : [];

  // Get SE files
  const sePath = path.join(ASSETS_DIR, 'audio/se');
  const ses = fs.existsSync(sePath)
    ? fs.readdirSync(sePath)
        .filter((f: string) => ['.mp3', '.wav', '.ogg'].includes(path.extname(f)))
        .map((f: string) => path.parse(f).name)
    : [];

  // Generate TypeScript types
  const content = `/**
 * Auto-generated asset types
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-asset-types.ts
 * 
 * Run: npm run generate-assets
 */

// Background image IDs
export type BackgroundId = ${backgrounds.length > 0 ? backgrounds.map((bg: string) => `'${bg}'`).join(' | ') : 'string'};

// BGM audio IDs
export type BgmId = ${bgms.length > 0 ? bgms.map((bgm: string) => `'${bgm}'`).join(' | ') : 'string'};

// Sound effect IDs
export type SeId = ${ses.length > 0 ? ses.map((se: string) => `'${se}'`).join(' | ') : 'string'};

// Asset counts for validation
export const ASSET_COUNTS = {
  backgrounds: ${backgrounds.length},
  bgm: ${bgms.length},
  se: ${ses.length},
} as const;

// All asset IDs for runtime validation
export const BACKGROUND_IDS = [${backgrounds.map((bg: string) => `'${bg}'`).join(', ')}] as const;
export const BGM_IDS = [${bgms.map((bgm: string) => `'${bgm}'`).join(', ')}] as const;
export const SE_IDS = [${ses.map((se: string) => `'${se}'`).join(', ')}] as const;
`;

  // Ensure types directory exists
  const typesDir = path.dirname(OUTPUT_FILE);
  if (!fs.existsSync(typesDir)) {
    fs.mkdirSync(typesDir, { recursive: true });
  }

  // Write the generated types
  fs.writeFileSync(OUTPUT_FILE, content, 'utf-8');

  console.log('✅ Asset types generated!');
  console.log(`   📁 Backgrounds: ${backgrounds.length}`);
  console.log(`   🎵 BGM: ${bgms.length}`);
  console.log(`   🔊 SE: ${ses.length}`);
  console.log(`   📄 Output: ${path.relative(process.cwd(), OUTPUT_FILE)}`);
}

// Run the generator
try {
  generateAssetTypes();
} catch (error) {
  console.error('❌ Error generating asset types:', error);
  process.exit(1);
}
